services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_server
    ports:
      - '8001:8000'
    volumes:
      - ./server:/server
    environment:
      - PYTHONUNBUFFERED=1
